steps:
  # Clone from GitHub repo
  - name: gcr.io/cloud-builders/git
    args: ["clone", "https://github.com/lightcoker/CatchyPass.git"]
  # Build images
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/catchypass/server-prod$SHORT_SHA",
        "./server",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/catchypass/client-prod$SHORT_SHA",
        "./client",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/catchypass/worker-prod$SHORT_SHA",
        "./worker",
      ]
  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/catchypass/server-prod$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/catchypass/client-prod$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/catchypass/worker-prod:$SHORT_SHA"]
  # deploy to GKE - prepare phase
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - prepare
      - --filename=./k8s/app/server-deployment.yaml
      - --image=asia.gcr.io/catchypass/server-prod:$SHORT_SHA
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - prepare
      - --filename=./k8s/app/client-deployment.yaml
      - --image=asia.gcr.io/catchypass/worker-prod:$SHORT_SHA
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - prepare
      - --filename=./k8s/app/worker-deployment.yaml
      - --image=asia.gcr.io/catchypass/worker-prod:$SHORT_SHA
  # deploy to GKE - apply phase
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - apply
      - --filename=./k8s/app
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER}
      - --timeout=10m0s
images:
  [
    "asia.gcr.io/catchypass/server-prod:$SHORT_SHA",
    "asia.gcr.io/catchypass/client-prod:$SHORT_SHA",
    "asia.gcr.io/catchypass/worker-prod:$SHORT_SHA",
  ]
