apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lightcoker@gapp.nthu.edu.tw
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          clouddns:
            project: catchypass
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
      - http01:
        ingress:
          class: nginx
