steps:
  # Clone from GitHub repo
  - name: gcr.io/cloud-builders/git
    args: ["clone", "https://github.com/lightcoker/CatchyPass.git"]
  # Trigger multiple builds
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Deploying databases"
        gcloud builds submit --project=catchypass --config=cloudbuild.db.yaml
        echo "Deploying apps"
        gcloud builds submit --project=catchypass --config=cloudbuild.app.yaml
