apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: lightcoker/catchypass-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: lightcoker/catchypass-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/app/server-deployment.yaml
      - k8s/app/server-clusterip.yaml
      - k8s/app/client-deployment.yaml
      - k8s/app/client-clusterip.yaml
