apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: asia.gcr.io/catchypass/client-prod
      context: client
      docker:
        dockerfile: Dockerfile
      # sync:
      #   manual:
      #     - src: "**/*.js"
      #       dest: .
      #     - src: "**/*.scss"
      #       dest: .
    - image: asia.gcr.io/catchypass/server-prod
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: asia.gcr.io/catchypass/worker-prod
      context: worker
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/deployment/server-deployment.yaml
      - k8s/deployment/client-deployment.yaml
      - k8s/deployment/worker-deployment.yaml
      - k8s/service/client-clusterip.yaml
      - k8s/service/server-clusterip.yaml
      - k8s/ingress-service-local.yaml
