apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: client
          image: asia.gcr.io/catchypass-290411/client-prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
