apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: worker
          image: asia.gcr.io/catchypass-290411/worker-prod
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redisnodeport
            - name: REDIS_PORT
              value: "6379"
          command: ["python", "-u", "worker.py"]
