apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: client
          image: asia.gcr.io/catchypass/catchypass-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
