apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: server
          image: lightcoker/catchypass-server
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb-nodeport
            - name: MONGO_USER
              value: mongo
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGO_PASSWORD
            - name: MONGO_PORT
              value: "27017"
            - name: REDIS_HOST
              value: redis-nodeport
            - name: REDIS_PORT
              value: "6379"
