apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: worker
          image: lightcoker/catchypass-worker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: REDIS_HOST
              value: redisnodeport
            - name: REDIS_PORT
              value: "6379"
