steps:
  # Clone from GitHub repo
  - name: gcr.io/cloud-builders/git
    args: ["clone", "https://github.com/lightcoker/CatchyPass.git"]
  # Build images
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/catchypass/mongo-prod:$SHORT_SHA",
        "--build-arg",
        "MONGO_INITDB_ROOT_PASSWORD=${_MONGO_INITDB_ROOT_PASSWORD}",
        "--build-arg",
        "MONGO_PASSWORD=${_MONGO_PASSWORD}",
        "./mongo",
      ]
  # Push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/catchypass/mongo-prod:$SHORT_SHA"]
  # deploy to GKE - prepare & apply phase
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/deployment/mongodb-deployment.yaml
      - --image=asia.gcr.io/catchypass/mongo-prod:$SHORT_SHA
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER}
      - --timeout=30m0s
images: ["asia.gcr.io/catchypass/mongo-prod:$SHORT_SHA"]
